base:
  'N': 10
  T: 11000
  T_train_val: 10000
  train_ratio: 0.8
  T_train: 8000
  T_val: 2000
  T_test: 1000
data_generation:
  load_data:
    node_mean: 50.0
    node_var: 10.0
    node_iid_var: 5.0
    node_theta: 0.9
  latency:
    mean: 0.0
    var: 0.0
    iid_var: 0.0
    theta: 0.0
exp4:
  batch_size: 64
  seq_length: 20
  input_size: 10
  output_size: 10
  num_workers: 24
  num_epochs: 100
  device: cuda
  mix_precision: true
  patience_epochs: 6
  min_delta: 0.001
  mode: min
  factor: 0.1
  patience_lr: 2
  min_lr: 1.0e-06
  threshold: 0.01
  ARconfig:
    order: 5
  LSTMConfig:
    learning_rate: 0.001
    hidden_size: 128
    num_layers: 4
    dropout_prob: 0.2
    weight_decay: 0.0001
  GNNConfig:
    learning_rate: 0.001
    hidden_size: 128
hidden_size: 102
num_layers: 3
dropout_prob: 0.31507582808498547
learning_rate: 0.007784421116708152
weight_decay: 0.00030763727804265344
factor: 0.10457911623121284
patience_lr: 2
threshold: 0.007191997097747425
batch_size: 36
num_epochs: 68
patience_epochs: 7
min_delta: 0.0004242904281004015
