base:
  'N': 10
  T: 11000
  T_train_val: 10000
  train_ratio: 0.8
  T_train: 8000
  T_val: 2000
  T_test: 1000
data_generation:
  load_data:
    node_load_mean_mean: 50.0
    node_load_mean_var: 10.0
    node_load_iid_var: 5.0
    node_load_ar1_theta: 0.9
  latency:
    node_latency_mean_mean: 30.0
    node_latency_mean_var: 10.0
    node_latency_ar1_theta: 0.9
exp4:
  batch_size: 64
  seq_length: 20
  input_size: 10
  output_size: 10
  learning_rate: 0.001
  num_workers: 16
  num_epochs: 100
  device: cuda
  mix_precision: true
  patience_epochs: 6
  min_delta: 0.001
  mode: min
  factor: 0.1
  patience_lr: 2
  min_lr: 1.0e-06
  threshold: 0.01
  ARconfig:
    order: 5
  LSTMconfig:
    hidden_size: 128
    num_layers: 4
    dropout_prob: 0.2
    weight_decay: 0.0001
  GNNconfig:
    hidden_size: 128
    num_layers: 4
hidden_size: 234
num_layers: 3
learning_rate: 0.0023489134109639306
weight_decay: 4.4703630998209476e-05
factor: 0.29532740085043363
patience_lr: 3
threshold: 0.009003188972922137
num_epochs: 92
patience_epochs: 8
min_delta: 3.9687169617626213e-05
